[versions]

compileSdk = "36"
targetSdk = "35"
minSdk = "24"
buildTools = "35.0.0"

androidGradlePlugin = "8.13.0"

# 2.2.0 is blocked becouse hilt worker does not support it
kotlin = "2.1.10"
hilt = "2.57.2"
googleServices = "4.4.4"
spotless = "8.0.0"
ksp = "2.1.10-1.0.30"
skie = "0.10.6"

hiltWorker = "1.3.0"
multidex = "2.0.1"
androidChart = "v3.1.0"
coroutines = "1.10.2"
coroutines-rx3 = "1.10.2"
googleMaterial = "1.13.0"
ktlint = "0.48.1"
fragmentViewBinding = "1.0.2"
firebase = "34.4.0"

androidx-fragment = "1.8.9"
androidx-lifecycle = "2.9.4"
androidx-lifecycle-extensions = "2.2.0"
androidx-navigation = "2.9.5"
androidx-constraintLayout = "2.2.1"
androidx-core = "1.17.0"
androidx-core-splashscreen = "1.0.1"
androidx-preferences = "1.2.1"
androidx-worker = "2.11.0"
androidx-recyclerView = "1.4.0"
androidx-security = "1.1.0"
androidx-room = "2.8.3"
androidx-appCompat = "1.7.1"
androidx-biometric = "1.1.0"
androidx-compose-core = "1.9.4"
androidx-activity-compose = "1.11.0"
androidx-material-icons-extended = "1.7.8"
androidx-compose-constraintLayout = "1.1.1"
androidx-compose-material3 = "1.4.0"
androidx-compose-material3-adaptive = "1.2.0"
androidx-car = "1.7.0"
androidx-glance-widget = "1.1.1"

rxjava = "3.1.12"
rxandroid = "3.0.2"
rxkoltin = "3.0.1"

retrofit = "3.0.0"
retrofit-logging = "5.2.1"

android-tools-desugar = "2.1.5"
jsoup = "1.21.2"
coil = "3.3.0"
guava = "33.5.0-android"
reorderable = "3.0.0"
google-barcode-scanner = "16.1.0"
timber = "5.0.1"

testing-junit = "4.13.2"
testing-hamcrest = "1.3"
testing-mockk = "1.14.6"
testing-assertj = "3.27.6"
testing-mockito = "5.20.0"
testing-mockito-kotlin = "6.1.0"
testing-androidx = "1.7.0"
testing-androidx-runner = "1.7.0"
testing-androidx-rules = "1.7.0"
testing-androidx-junit-extension = "1.3.0"
testing-androidx-arch-core = "2.2.0"

kotlinx-serialization = "1.8.1" # newer version is not compiling on iOS
kotlinx-datetime = "0.6.2" # newer version is not compiling on iOS
kotlin-bitops-endian = "0.2.0" # newer version is not compiling on iOS

googleJavaFormat = "1.19.2"

[libraries]
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
androidChart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "androidChart" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-rx3 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-rx3", version.ref = "coroutines-rx3" }
googleMaterial = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
fragmentViewBinding = { group = "com.github.Zhuinden", name = "fragmentviewbindingdelegate-kt", version.ref = "fragmentViewBinding" }

hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-worker = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWorker" }
hilt-kapt = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-worker-kapt = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltWorker" }

androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintLayout" }
androidx-preferences = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preferences" }
androidx-recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerView" }
androidx-worker = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-worker" }
androidx-appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appCompat" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidx-biometric" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-core-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "androidx-lifecycle-extensions" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "androidx-security" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-rxjava = { group = "androidx.room", name = "room-rxjava3", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose-core" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-compose-core" }
androidx-compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-compose-core" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidx-material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidx-compose-constraintLayout" }
androidx-car-app = { group = "androidx.car.app", name = "app", version.ref = "androidx-car" }
androidx-glance-widget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "androidx-glance-widget" }
androidx-glance-material = { group = "androidx.glance", name = "glance-material3", version.ref = "androidx-glance-widget" }
androidx-glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "androidx-glance-widget" }
androidx-glance-widget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "androidx-glance-widget" }

rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
rxkotlin = { group = "com.github.reactivex", name = "rxkotlin", version.ref = "rxkoltin" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-rxJavaAdapter = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }
retrofit-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "retrofit-logging" }

firebase = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }

kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

android-tools-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "android-tools-desugar" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
google-barcode-scanner = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "google-barcode-scanner" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

kotlin-bitops-endian = { group = "org.kotlincrypto.bitops", name = "endian", version.ref = "kotlin-bitops-endian" }

testing-junit = { group = "junit", name = "junit", version.ref = "testing-junit" }
testing-hamcrest = { group = "org.hamcrest", name = "hamcrest-all", version.ref = "testing-hamcrest" }
testing-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
testing-mockk = { group = "io.mockk", name = "mockk", version.ref = "testing-mockk" }
testing-assertj = { group = "org.assertj", name = "assertj-core", version.ref = "testing-assertj" }
testing-mockito = { group = "org.mockito", name = "mockito-core", version.ref = "testing-mockito" }
testing-mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "testing-mockito-kotlin" }
testing-androidx = { group = "androidx.test", name = "core", version.ref = "testing-androidx" }
testing-androidx-navigation = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidx-navigation" }
testing-androidx-runner = { group = "androidx.test", name = "runner", version.ref = "testing-androidx-runner" }
testing-androidx-rules = { group = "androidx.test", name = "rules", version.ref = "testing-androidx-rules" }
testing-androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "testing-androidx-junit-extension" }
testing-androidx-arch-core = { group = "androidx.arch.core", name = "core-testing", version.ref = "testing-androidx-arch-core" }
testing-kotlin-relfect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }